package io.openems.edge.evcs.technagon;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.evcs.technagon.enums.TechnagonChargingPoint;

@ObjectClassDefinition(//
		name = "EVCS Technagon Charger", //
		description = "Implements the Technagon Charger.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "evcs0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Debug Mode", description = "Activates the debug mode")
	boolean debugMode() default false;

	@AttributeDefinition(name = "Read only", description = "Defines whether this evcs is read only.", required = true)
	boolean readOnly() default false;

	@AttributeDefinition(name = "Charging point", description = "The charging point of the station.")
	TechnagonChargingPoint charging_point() default TechnagonChargingPoint.CHARGING_POINT_1;

	@AttributeDefinition(name = "Minimum hardware current", description = "Minimum current the charger can use per phase in mA. The effective minimum current will be the maximum of this configured value and the value reported by the EVCS.", required = true)
	int minHwCurrent() default 6000;

	@AttributeDefinition(name = "Maximum hardware current", description = "Maximum current the charger can use per phase in mA. The effective maximum current will be the minimum of this configured value and the value reported by the EVCS.", required = true)
	int maxHwCurrent() default 32000;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "EVCS Technagon Charger [{id}]";

}